In [1]:
import requests

In [2]:
URL = "https://api.alquran.cloud/v1/quran/en.asad"

res = requests.get(URL)
res

In [16]:
json_data = res.json()

In [4]:
import pandas as pd

In [5]:
df = pd.json_normalize(json_data["data"])
df

,surahs,edition.identifier,edition.language,edition.name,edition.englishName,edition.format,edition.type
0,"[{'number': 1, 'name': 'سُورَةُ ٱلْفَاتِحَةِ',...",en.asad,en,Asad,Muhammad Asad,text,translation

In [15]:
df.loc[0:2]

,surahs,edition.identifier,edition.language,edition.name,edition.englishName,edition.format,edition.type
0,"[{'number': 1, 'name': 'سُورَةُ ٱلْفَاتِحَةِ',...",en.asad,en,Asad,Muhammad Asad,text,translation