In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("08_Data_cleaning.csv")

In [3]:
#cleaning missing values
print(df.isnull())
print(df.isnull().sum())
print(df.dropna())

       id   name    age  country  gender
0   False  False  False    False   False
1   False  False  False    False   False
2   False  False   True    False   False
3   False  False   True    False   False
4   False  False  False    False   False
5   False  False  False    False   False
6   False   True  False    False   False
7   False  False  False     True   False
8   False  False  False    False   False
9   False  False   True    False   False
10  False  False  False    False    True
id         0
name       1
age        3
country    1
gender     1
dtype: int64
   id          name   age country  gender
0   1      john doe  29.0     usa    male
1   1      john doe  29.0     usa    male
4   4  maria garcia  43.0   spain  female
5   5        li wei  27.0   china    male
8   8     rachellee  29.0     usa  female

In [4]:
#FILLINF AGE VALUES
fill_age = df.copy()
age_mean = fill_age["age"].mean()
fill_age["age"] = fill_age["age"].fillna(age_mean)
fill_age

    id          name     age country   gender
0    1      john doe  29.000     usa     male
1    1      john doe  29.000     usa     male
2    2    jane smith  33.875  canada   female
3    3          alex  33.875     usa  unknown
4    4  maria garcia  43.000   spain   female
5    5        li wei  27.000   china     male
6    6           NaN  45.000   india   female
7    7    ahmad khan  38.000     NaN     male
8    8     rachellee  29.000     usa   female
9    9   carlos ruiz  33.875  maxico     male
10  10   emily davis  31.000     usa      NaN

In [10]:
#farword fill
df.ffill()

    id          name   age country   gender
0    1      john doe  29.0     usa     male
1    1      john doe  29.0     usa     male
2    2    jane smith  29.0  canada   female
3    3          alex  29.0     usa  unknown
4    4  maria garcia  43.0   spain   female
5    5        li wei  27.0   china     male
6    6        li wei  45.0   india   female
7    7    ahmad khan  38.0   india     male
8    8     rachellee  29.0     usa   female
9    9   carlos ruiz  29.0  maxico     male
10  10   emily davis  31.0     usa     male

In [9]:
#backword fill
df.bfill()

    id          name   age country   gender
0    1      john doe  29.0     usa     male
1    1      john doe  29.0     usa     male
2    2    jane smith  43.0  canada   female
3    3          alex  43.0     usa  unknown
4    4  maria garcia  43.0   spain   female
5    5        li wei  27.0   china     male
6    6    ahmad khan  45.0   india   female
7    7    ahmad khan  38.0     usa     male
8    8     rachellee  29.0     usa   female
9    9   carlos ruiz  31.0  maxico     male
10  10   emily davis  31.0     usa      NaN