In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("08_Data_cleaning.csv")
df

    id          name   age country   gender
0    1      john doe  29.0     usa     male
1    1      john doe  29.0     usa     male
2    2    jane smith   NaN  canada   female
3    3          alex   NaN     usa  unknown
4    4  maria garcia  43.0   spain   female
5    5        li wei  27.0   china     male
6    6           NaN  45.0   india   female
7    7    ahmad khan  38.0     NaN     male
8    8     rachellee  29.0     usa   female
9    9   carlos ruiz   NaN  maxico     male
10  10   emily davis  31.0     usa      NaN

In [5]:
#Handle duplicate values
df["country"].duplicated()

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [7]:
#Delecte duplicate values
du_df = df.copy()
du_df = du_df.drop_duplicates()
du_df

    id          name   age country   gender
0    1      john doe  29.0     usa     male
2    2    jane smith   NaN  canada   female
3    3          alex   NaN     usa  unknown
4    4  maria garcia  43.0   spain   female
5    5        li wei  27.0   china     male
6    6           NaN  45.0   india   female
7    7    ahmad khan  38.0     NaN     male
8    8     rachellee  29.0     usa   female
9    9   carlos ruiz   NaN  maxico     male
10  10   emily davis  31.0     usa      NaN