In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("08_Data_cleaning.csv")
df

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [27]:
#apply
df2 = df.copy()
def tax(x):
    if(x>50000):        
        return x + x*0.2
    else:
        return x + x*0.1
df2["income"] = df2["income"].apply(tax)
df2

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  66000.0
1    1      john doe  29.0     usa     male  66000.0
2    2    jane smith   NaN  canada   female  74400.0
3    3          alex   NaN     usa  unknown  51700.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  61200.0
6    6           NaN  45.0   india   female  87600.0
7    7    ahmad khan  38.0     NaN     male  81600.0
8    8     rachellee  29.0     usa   female  74400.0
9    9   carlos ruiz   NaN  maxico     male  49500.0
10  10   emily davis  31.0     usa      NaN  69600.0

In [20]:
#map
gender_map ={"male": "M","female":"F","unknown":"U"}
df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      john doe  29.0     usa      M  55000.0  20%
1    1      john doe  29.0     usa      M  55000.0  20%
2    2    jane smith   NaN  canada      F  62000.0  20%
3    3          alex   NaN     usa      U  47000.0  10%
4    4  maria garcia  43.0   spain      F      NaN  10%
5    5        li wei  27.0   china      M  51000.0  20%
6    6           NaN  45.0   india      F  73000.0  20%
7    7    ahmad khan  38.0     NaN      M  68000.0  20%
8    8     rachellee  29.0     usa      F  62000.0  20%
9    9   carlos ruiz   NaN  maxico      M  45000.0  10%
10  10   emily davis  31.0     usa    NaN  58000.0  20%

In [24]:
#assign
df2.assign(new_income = df2["income"] *1.1)

    id          name   age country   gender   income  new_income
0    1      john doe  29.0     usa     male  55000.0     60500.0
1    1      john doe  29.0     usa     male  55000.0     60500.0
2    2    jane smith   NaN  canada   female  62000.0     68200.0
3    3          alex   NaN     usa  unknown  47000.0     51700.0
4    4  maria garcia  43.0   spain   female      NaN         NaN
5    5        li wei  27.0   china     male  51000.0     56100.0
6    6           NaN  45.0   india   female  73000.0     80300.0
7    7    ahmad khan  38.0     NaN     male  68000.0     74800.0
8    8     rachellee  29.0     usa   female  62000.0     68200.0
9    9   carlos ruiz   NaN  maxico     male  45000.0     49500.0
10  10   emily davis  31.0     usa      NaN  58000.0     63800.0

In [26]:
#replace(old,new): replaces old values with some new values (repace USA with US)
df2["country"].replace("usa","United States")

0     United States
1     United States
2            canada
3     United States
4             spain
5             china
6             india
7               NaN
8     United States
9            maxico
10    United States
Name: country, dtype: object