In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("08_Data_cleaning.csv")
df

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [3]:
#rename all columns
df2 = df.copy()
df2.columns = ["Id","Name","Age","Country","Gender","Income"]  #captilizing all columns

In [4]:
#Renaming a perticular column
df2.rename(columns = {"Income": "Salary"})

    Id          Name   Age Country   Gender   Salary
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [5]:
#RENAMEING PERTICLAR ROW'S INDEX
df2.rename(index = {0: "first"})

       Id          Name   Age Country   Gender   Income
first   1      john doe  29.0     usa     male  55000.0
1       1      john doe  29.0     usa     male  55000.0
2       2    jane smith   NaN  canada   female  62000.0
3       3          alex   NaN     usa  unknown  47000.0
4       4  maria garcia  43.0   spain   female      NaN
5       5        li wei  27.0   china     male  51000.0
6       6           NaN  45.0   india   female  73000.0
7       7    ahmad khan  38.0     NaN     male  68000.0
8       8     rachellee  29.0     usa   female  62000.0
9       9   carlos ruiz   NaN  maxico     male  45000.0
10     10   emily davis  31.0     usa      NaN  58000.0

In [12]:
#sorting values
#df2["Income"].sort_values()
#or
df2 = df2.sort_values("Income",ascending=False)
print(df2)
df2 = df2.reset_index(drop = True)
df2

    Id          Name   Age Country   Gender   Income
0    6           NaN  45.0   india   female  73000.0
1    7    ahmad khan  38.0     NaN     male  68000.0
2    2    jane smith   NaN  canada   female  62000.0
3    8     rachellee  29.0     usa   female  62000.0
4   10   emily davis  31.0     usa      NaN  58000.0
5    1      john doe  29.0     usa     male  55000.0
6    1      john doe  29.0     usa     male  55000.0
7    5        li wei  27.0   china     male  51000.0
8    3          alex   NaN     usa  unknown  47000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10   4  maria garcia  43.0   spain   female      NaN

    Id          Name   Age Country   Gender   Income
0    6           NaN  45.0   india   female  73000.0
1    7    ahmad khan  38.0     NaN     male  68000.0
2    2    jane smith   NaN  canada   female  62000.0
3    8     rachellee  29.0     usa   female  62000.0
4   10   emily davis  31.0     usa      NaN  58000.0
5    1      john doe  29.0     usa     male  55000.0
6    1      john doe  29.0     usa     male  55000.0
7    5        li wei  27.0   china     male  51000.0
8    3          alex   NaN     usa  unknown  47000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10   4  maria garcia  43.0   spain   female      NaN

In [10]:
#sorting on the bases of index
df2.sort_index()

    Id          Name   Age Country   Gender   Income
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [14]:
#assigns rank
df2["Ranking"] = df2["Income"].rank()
df2

    Id          Name   Age Country   Gender   Income  Ranking
0    6           NaN  45.0   india   female  73000.0     10.0
1    7    ahmad khan  38.0     NaN     male  68000.0      9.0
2    2    jane smith   NaN  canada   female  62000.0      7.5
3    8     rachellee  29.0     usa   female  62000.0      7.5
4   10   emily davis  31.0     usa      NaN  58000.0      6.0
5    1      john doe  29.0     usa     male  55000.0      4.5
6    1      john doe  29.0     usa     male  55000.0      4.5
7    5        li wei  27.0   china     male  51000.0      3.0
8    3          alex   NaN     usa  unknown  47000.0      2.0
9    9   carlos ruiz   NaN  maxico     male  45000.0      1.0
10   4  maria garcia  43.0   spain   female      NaN      NaN