## Shift id column to the end

In [2]:
import pandas as pd

In [10]:
df = pd.read_csv("08_Data_cleaning.csv")
df

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [27]:
df2 = df.copy()
column_names = [col for col in df2.columns if col != "id"]    #List comprehension
df2 = df2[column_names + ["id"]]
df2

            name   age country   gender   income  id
0       john doe  29.0     usa     male  55000.0   1
1       john doe  29.0     usa     male  55000.0   1
2     jane smith   NaN  canada   female  62000.0   2
3           alex   NaN     usa  unknown  47000.0   3
4   maria garcia  43.0   spain   female      NaN   4
5         li wei  27.0   china     male  51000.0   5
6            NaN  45.0   india   female  73000.0   6
7     ahmad khan  38.0     NaN     male  68000.0   7
8      rachellee  29.0     usa   female  62000.0   8
9    carlos ruiz   NaN  maxico     male  45000.0   9
10   emily davis  31.0     usa      NaN  58000.0  10