In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("08_Data_cleaning.csv")
df

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [3]:
df2 = df.copy()
df2

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [4]:
#drop duplicated rows
df2 = df2.drop_duplicates()
df2

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [5]:
#Fill income and age  NAN values with 0
df2[["income","age"]] = df2[["income","age"]].fillna(0)
#fill gender and name unknown values with Male and NAN with male
df2["gender"] = df2["gender"].replace("unknown","male").fillna("male")
#FILL COUNTRY NAN Values with UNknown
df2["country"] = df2["country"].fillna("unknown")
#fill name NAN values with Unknown
df2["name"] = df2["name"].fillna("unknown")
df2

C:\Users\hp\AppData\Local\Temp\ipykernel_4248\667895298.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[["income","age"]] = df2[["income","age"]].fillna(0)
C:\Users\hp\AppData\Local\Temp\ipykernel_4248\667895298.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["gender"] = df2["gender"].replace("unknown","male").fillna("male")
C:\Users\hp\AppData\Local\Temp\ipykernel_4248\667895298.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["country"] = df2["country"].fillna("unknown")
C:\Users\hp\AppData\Local\Temp\ipykernel_4248\667895298.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["name"] = df2["name"].fillna("unknown")

    id          name   age  country  gender   income
0    1      john doe  29.0      usa    male  55000.0
2    2    jane smith   0.0   canada  female  62000.0
3    3          alex   0.0      usa    male  47000.0
4    4  maria garcia  43.0    spain  female      0.0
5    5        li wei  27.0    china    male  51000.0
6    6       unknown  45.0    india  female  73000.0
7    7    ahmad khan  38.0  unknown    male  68000.0
8    8     rachellee  29.0      usa  female  62000.0
9    9   carlos ruiz   0.0   maxico    male  45000.0
10  10   emily davis  31.0      usa    male  58000.0

In [7]:
#sort the dataframe on the basis of income
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop = True)
df2

   id          name   age  country  gender   income
0   4  maria garcia  43.0    spain  female      0.0
1   9   carlos ruiz   0.0   maxico    male  45000.0
2   3          alex   0.0      usa    male  47000.0
3   5        li wei  27.0    china    male  51000.0
4   1      john doe  29.0      usa    male  55000.0
5  10   emily davis  31.0      usa    male  58000.0
6   2    jane smith   0.0   canada  female  62000.0
7   8     rachellee  29.0      usa  female  62000.0
8   7    ahmad khan  38.0  unknown    male  68000.0
9   6       unknown  45.0    india  female  73000.0

In [8]:
#store the data into new csv file
df2.to_csv("15_Sorted Data_of_08_csv_file.csv")

In [9]:
#store the data into new json file
df2.to_json("15_Sorted Data_of_08_csv_file.json")