In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("08_Data_cleaning.csv")
df

    id          name   age country   gender   income
0    1      john doe  29.0     usa     male  55000.0
1    1      john doe  29.0     usa     male  55000.0
2    2    jane smith   NaN  canada   female  62000.0
3    3          alex   NaN     usa  unknown  47000.0
4    4  maria garcia  43.0   spain   female      NaN
5    5        li wei  27.0   china     male  51000.0
6    6           NaN  45.0   india   female  73000.0
7    7    ahmad khan  38.0     NaN     male  68000.0
8    8     rachellee  29.0     usa   female  62000.0
9    9   carlos ruiz   NaN  maxico     male  45000.0
10  10   emily davis  31.0     usa      NaN  58000.0

In [6]:
#GROUPIN: ON THE BASIS OF COUNTRY
print(df.groupby("country")["income"].mean())
print(df.groupby("country")["income"].min())

country
canada    62000.0
china     51000.0
india     73000.0
maxico    45000.0
spain         NaN
usa       55400.0
Name: income, dtype: float64
country
canada    62000.0
china     51000.0
india     73000.0
maxico    45000.0
spain         NaN
usa       47000.0
Name: income, dtype: float64

In [17]:
df.groupby("gender")["age"].mean()

pandas.core.series.Series

In [12]:
df.groupby("country")["income"].agg(["mean","median","min","max"])

            mean   median      min      max
country
canada   62000.0  62000.0  62000.0  62000.0
china    51000.0  51000.0  51000.0  51000.0
india    73000.0  73000.0  73000.0  73000.0
maxico   45000.0  45000.0  45000.0  45000.0
spain        NaN      NaN      NaN      NaN
usa      55400.0  55000.0  47000.0  62000.0

In [16]:
df4 = df.groupby("country")["income"].agg(["mean","median","min","max"])
df4

            mean   median      min      max
country
canada   62000.0  62000.0  62000.0  62000.0
china    51000.0  51000.0  51000.0  51000.0
india    73000.0  73000.0  73000.0  73000.0
maxico   45000.0  45000.0  45000.0  45000.0
spain        NaN      NaN      NaN      NaN
usa      55400.0  55000.0  47000.0  62000.0

In [18]:
df4 = df.groupby("country")["income"].agg(min_salary = "min",max_salary = "max",avg_salary ="mean")
df4

         min_salary  max_salary  avg_salary
country
canada      62000.0     62000.0     62000.0
china       51000.0     51000.0     51000.0
india       73000.0     73000.0     73000.0
maxico      45000.0     45000.0     45000.0
spain           NaN         NaN         NaN
usa         47000.0     62000.0     55400.0

In [19]:
df.groupby("country").agg({"income":"mean","age":"mean"})

          income   age
country
canada   62000.0   NaN
china    51000.0  27.0
india    73000.0  45.0
maxico   45000.0   NaN
spain        NaN  43.0
usa      55400.0  29.5

In [23]:
df.groupby("country").agg(avg_income = ("income","mean"),min_age = ("age","min"))

         avg_income  min_age
country
canada      62000.0      NaN
china       51000.0     27.0
india       73000.0     45.0
maxico      45000.0      NaN
spain           NaN     43.0
usa         55400.0     29.0