In [2]:
import pandas as pd

In [4]:
df_customers = pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name": ["adnan","ubaid","moshin","kamran"]
})
df_orders = pd.DataFrame({
    "order_id":[101,102,103,104],
    "customer_id":[2,1,4,5],
    "amount":[250,120,300,180]
})

In [5]:
df_customers

   customer_id    name
0            1   adnan
1            2   ubaid
2            3  moshin
3            4  kamran

In [6]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [7]:
#inner join
pd.merge(df_customers,df_orders,on="customer_id")

   customer_id    name  order_id  amount
0            1   adnan       102     120
1            2   ubaid       101     250
2            4  kamran       103     300

In [8]:
#left join
pd.merge(df_customers,df_orders,on="customer_id",how = "left")

   customer_id    name  order_id  amount
0            1   adnan     102.0   120.0
1            2   ubaid     101.0   250.0
2            3  moshin       NaN     NaN
3            4  kamran     103.0   300.0

In [9]:
#right join
pd.merge(df_customers,df_orders,on="customer_id",how = "right")

   customer_id    name  order_id  amount
0            2   ubaid       101     250
1            1   adnan       102     120
2            4  kamran       103     300
3            5     NaN       104     180

In [10]:
#outer join
pd.merge(df_customers,df_orders,on="customer_id",how = "outer")

   customer_id    name  order_id  amount
0            1   adnan     102.0   120.0
1            2   ubaid     101.0   250.0
2            3  moshin       NaN     NaN
3            4  kamran     103.0   300.0
4            5     NaN     104.0   180.0